//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSalInsurenceDiskFactory
    {
        public int insAutoID { get; set; }
        /// <summary>
        /// کد کارگاه
        /// </summary>
        public string DSK_ID { get; set; }
        /// <summary>
        /// نام کارگاه
        /// </summary>
        public string DSK_NAME { get; set; }
        /// <summary>
        /// نام کارفرما 
        /// </summary>
        public string DSK_FARM { get; set; }
        /// <summary>
        /// آدرس کارگاه
        /// </summary>
        public string DSK_ADRS { get; set; }
        /// <summary>
        /// نوع لیست
        /// </summary>
        public int DSK_KIND { get; set; }
        /// <summary>
        /// سال عملکرد
        /// </summary>
        public int DSK_YY { get; set; }
        /// <summary>
        /// ماه عملکرد
        /// </summary>
        public int DSK_MM { get; set; }
        /// <summary>
        /// شماره لیست
        /// </summary>
        public string DSK_LISTNO { get; set; }
        /// <summary>
        /// توضیحات لیست
        /// </summary>
        public string DSK_DISC { get; set; }
        /// <summary>
        /// تعداد کارکنان
        /// </summary>
        public int DSK_NUM { get; set; }
        /// <summary>
        /// مجموع روز های کارکرد
        /// </summary>
        public int DSK_TDD { get; set; }
        /// <summary>
        /// مجموع دستمزد روزانه
        /// </summary>
        public int DSK_TROOZ { get; set; }
        /// <summary>
        /// مجموع دستمزد ماهانه
        /// </summary>
        public int DSK_TMAH { get; set; }
        /// <summary>
        /// مجموع مزایای ماهانه مشمول
        /// </summary>
        public int DSK_TMAZ { get; set; }
        /// <summary>
        /// مجموع دستمزد و مزایای ماهانه مشمول
        /// </summary>
        public int DSK_TMASH { get; set; }
        /// <summary>
        /// مجموع کل مزایای ماهانه( مشمول و غیر مشمول)
        /// </summary>
        public int DSK_TTOTL { get; set; }
        /// <summary>
        /// مجموع حق بیمه سهم بیمه شده
        /// </summary>
        public int DSK_TBIME { get; set; }
        /// <summary>
        /// مجموع حق بیمه سهم کارفرما
        /// </summary>
        public int DSK_TKOSO { get; set; }
        /// <summary>
        /// مجموع حق بیمه بیکاری
        /// </summary>
        public int DSK_BIC { get; set; }
        /// <summary>
        /// نرخ حق بیمه
        /// </summary>
        public int DSK_RATE { get; set; }
        /// <summary>
        /// نرخ حق پورسانتاژ
        /// </summary>
        public int DSK_PRATE { get; set; }
        /// <summary>
        /// نرخ مشاغل سخت زیان آور
        /// </summary>
        public int DSK_BIMH { get; set; }
        /// <summary>
        /// ردیف پیمان
        /// </summary>
        public string MON_PYM { get; set; }
    }
}
