//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalInsurenceDiskPersonal
    {
        public int insAutoID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string piPersonalID { get; set; }
        /// <summary>
        /// کد کارگاه
        /// </summary>
        public string DSW_ID { get; set; }
        /// <summary>
        /// سال عملکرد
        /// </summary>
        public int DSW_YY { get; set; }
        /// <summary>
        /// ماه عملکرد
        /// </summary>
        public int DSW_MM { get; set; }
        /// <summary>
        /// شماره لیست
        /// </summary>
        public string DSW_LISTNO { get; set; }
        /// <summary>
        /// شماره بیمه
        /// </summary>
        public string DSW_ID1 { get; set; }
        /// <summary>
        /// نام
        /// </summary>
        public string DSW_FNAME { get; set; }
        /// <summary>
        /// نام خانوادگی
        /// </summary>
        public string DSW_LNAME { get; set; }
        /// <summary>
        /// نام پدر
        /// </summary>
        public string DSW_DNAME { get; set; }
        /// <summary>
        /// شماره شناسنامه
        /// </summary>
        public string DSW_IDNO { get; set; }
        /// <summary>
        /// محل صدور
        /// </summary>
        public string DSW_IDPLC { get; set; }
        /// <summary>
        /// تاریخ صدور
        /// </summary>
        public string DSW_IDATE { get; set; }
        /// <summary>
        /// تاریخ تولد
        /// </summary>
        public string DSW_BDATE { get; set; }
        /// <summary>
        /// جنسیت
        /// </summary>
        public string DSW_SEX { get; set; }
        /// <summary>
        /// ملیت
        /// </summary>
        public string DSW_NAT { get; set; }
        /// <summary>
        /// شرح شغل
        /// </summary>
        public string DSW_OCP { get; set; }
        /// <summary>
        /// تاریخ شروع به کار
        /// </summary>
        public string DSW_SDATE { get; set; }
        /// <summary>
        /// تاریخ ترک کار
        /// </summary>
        public string DSW_EDATE { get; set; }
        /// <summary>
        /// تعداد روز های کارکرد
        /// </summary>
        public int DSW_DD { get; set; }
        /// <summary>
        /// دستمزد روزانه
        /// </summary>
        public int DSW_ROOZ { get; set; }
        /// <summary>
        /// دستمزد ماهانه
        /// </summary>
        public int DSW_MAH { get; set; }
        /// <summary>
        /// مزایای ماهانه
        /// </summary>
        public int DSW_MAZ { get; set; }
        /// <summary>
        /// جمع دستمزد و مزایای ماهانه مشمول
        /// </summary>
        public int DSW_MASH { get; set; }
        /// <summary>
        /// جمع کل دستمزد و مزایای ماهانه
        /// </summary>
        public int DSW_TOTL { get; set; }
        /// <summary>
        /// حق بیمه سهم بیمه شده
        /// </summary>
        public int DSW_BIME { get; set; }
        /// <summary>
        /// نرخ پورسانتاژ
        /// </summary>
        public int DSW_PRATE { get; set; }
        /// <summary>
        /// کد شغل
        /// </summary>
        public string DSW_JOB { get; set; }
        /// <summary>
        /// کد ملی
        /// </summary>
        public string PER_NATCOD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int DayAddCount { get; set; }
    }
}
